author: billofbong
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: org.awesomecraft.plugins.killer.Killer
name: Killer
startup: postworld
url: http://awesomecraft.org/
version: '1.0'
permissions:
  killer.kill:
    default: OP
commands:
  blazekill:
    description: Lets you kill with a blaze rod